### ISSUE TITLE
GSoC: Should tunneldigger participate

### ISSUE THREAD

**Issue by mitar** [wlanslovenija/tunneldigger#117]
If you would like tthat tunneldigger participates with some ideas in GSoC this year, consider adding those ideas to [this list of projects](https://github.com/freifunk/projects.freifunk.net-contents). You could list it under wlan slovenija network or some other one, whatever you prefer.

So main question is if there is anyone willing to mentor somebody else. And what are those ideas they could work on. Maybe better instrumentation, some better debugging/status printing, some things like that?

If you already know of anyone with student status who would be interested in contributing and getting payed for that a bit, they can also apply and this is valid as well.

**Comment by kaechele** [comment]
I'd be willing to mentor.
An idea that I had would be an automatically load-balancing (and re-balancing) Tunneldigger broker cluster based on the overall bandwidth use of each Tunnel.
This could fix a problem we are seeing: About 5% of our clients use 80% of our bandwidth. Sometimes it happens that all 5% of these clients land on one gateway (broker instance). With this we could move them gracefully to a new broker.

**Comment by mitar** [comment]
Cool. Feel free to make a PR to that repo.

**Comment by kaechele** [comment]
Given that there is a community bonding phase in GSoC it would be good to know what channel of communication we should formalize for Tunneldigger.
GitHub exclusively?
I see the wlanslovenija trac is down. The Rocket Chat instance is still up at chat.wlan-si.net but it is not mentioned anywhere and there is minimal activity there. If you try to find the contact info at wlan-si.net you get to a contact form (where I don't know where this goes) or you are linked to the dead trac instance for a Wiki on Mailinglists and RocketChat.

So all in all not a very good basis for communication.
Maybe IRC would be an option? Most of the Freifunk people are on the hackint Network. We could create a channel there. Otherwise FreeNode seems like a popular option as well.

**Comment by mitar** [comment]
Yes, for now I would advise against using wlan slovenija infrastructure. But that is also not needed, for bonding period generally [this mailing list is used](https://lists.freifunk.net/mailman/listinfo/wlanware-freifunk.net). See [FAQ](https://projects.freifunk.net/#/faq) here. And then also direct contact with the mentor, and you decide how you want that to be.

I am in favor of updating the top-level README and removing the "Source Code, Issue Tracker and Mailing List" section and just point to GitHub for now for all communication about development.

**Comment by RalfJung** [comment]
> I am in favor of updating the top-level README and removing the "Source Code, Issue Tracker and Mailing List" section and just point to GitHub for now for all communication about development.

Agreed.

**Comment by kaechele** [comment]
See #118

**Comment by mitar** [comment]
FYI, You should add your GSoC idea to that repo soon.

**Comment by RalfJung** [comment]
This can probably be closed, the list of GSoC projects has long been finalized.
