### ISSUE TITLE
Sync version number with openwrt/lede package

### ISSUE THREAD

**Issue by kaechele** [wlanslovenija/tunneldigger#73]
The openwrt package currently lists a different version than is tagged in the tunneldigger repo.
We should work to keep them in sync in the future.

**Comment by kaechele** [comment]
See also: https://github.com/wlanslovenija/firmware-packages-opkg/pull/11

**Comment by RalfJung** [comment]
Releasing a new version for the fix with new kernels makes sense, I think. I was going to advocate for that once #66 is merged.

**Comment by robimarko** [comment]
I think that I will tag a new version soon, but still gotta think what the appropriate version would be.
I mean, we can move to 1.0 as far as I am concerned

**Comment by RalfJung** [comment]
I am not sure about 1.0, maybe that should wait for IPv6 support and some more research into figuring out why we need all that NAT hackery?

gluon, which also includes a tunneldigger package, seems to just use date and git SHA instead of a version number, so there is no version constraint there. Looking at https://github.com/wlanslovenija/firmware-packages-opkg/blob/master/net/tunneldigger/Makefile, maybe the next version should be 0.5.0?

@robimarko what does it take to make a version, beyond pushing a tag?

**Comment by robimarko** [comment]
Well, we can wait for IPv6 but I don't think that anybody is developing Tunneldigger at all.

In Otvorena mreza we also use latest GIT tag.

We can simply push a tag and edit it in source as its referenced couple of times

**Comment by RalfJung** [comment]
Just to be clear, I think 0.5 is fine any time, just for 1.0 I feel it should be "more ready". But I don't care strongly, and I certainly agree it's about time to have a tag again.

**Comment by robimarko** [comment]
For me 0.5 is fine also, its been way too long and a lot of changes in meantime have happened.
Only issue I am having current commit is that init script on OpenWrt for broker is broken.

**Comment by RalfJung** [comment]
@pmelange can you make sure that the version 0.4.0 is getting used properly on the lede side?

**Comment by pmelange** [comment]
Yes, doing a test build now.

**Comment by pmelange** [comment]
> @pmelange can you make sure that the version 0.4.0 is getting used properly on the lede side?

Merged https://github.com/openwrt/packages/pull/21752

**Comment by pmelange** [comment]
Please feel free to close this issue
